### ISSUE TITLE
Very slow to compile compared to the fp books repo

### ISSUE THREAD

**Issue by arobson73** [scala-exercises/exercises-fpinscala#33]
I know this is not so helpful. compiling it is so slow. if i make a single line change in a source file, then 
i have to wait 30 to 60 seconds for it to compile. 
The fp book's repo from github compiles very fast (single line change in a source file take 1 second to run). i can see the build.sbt for that is very lean in the fp book. 
I'd help out but don't really know enough sbt yet.

**Comment by raulraja** [comment]
@arobson73 You are not supposed to compile the exercises yourself or even run this project locally to complete them. The exercises are available online at https://www.scala-exercises.org/fp_in_scala/getting_started_with_functional_programming You may just login with your github account and do all the exercises in your browser.

**Comment by arobson73** [comment]
oh i see. thanks.
